# Site settings
title: Nate Hill
email: nathanielhill@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: natenatenate
github_username:  natehill

# Build settings
markdown: kramdown
